version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # ignore updates of minor importance
      - dependency-name: "git"
        update-types: ["version-update:semver-patch"]
